//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsbleTest.AssignmentSubmission {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="AssignmentSubmission.AssignmentSubmissionService")]
    public interface AssignmentSubmissionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AssignmentSubmissionService/SubmitAssignment", ReplyAction="urn:AssignmentSubmissionService/SubmitAssignmentResponse")]
        void SubmitAssignment(int assignmentId, byte[][] data, string authToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AssignmentSubmissionService/SubmitAssignment", ReplyAction="urn:AssignmentSubmissionService/SubmitAssignmentResponse")]
        System.Threading.Tasks.Task SubmitAssignmentAsync(int assignmentId, byte[][] data, string authToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AssignmentSubmissionServiceChannel : OsbleTest.AssignmentSubmission.AssignmentSubmissionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AssignmentSubmissionServiceClient : System.ServiceModel.ClientBase<OsbleTest.AssignmentSubmission.AssignmentSubmissionService>, OsbleTest.AssignmentSubmission.AssignmentSubmissionService {
        
        public AssignmentSubmissionServiceClient() {
        }
        
        public AssignmentSubmissionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AssignmentSubmissionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssignmentSubmissionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssignmentSubmissionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SubmitAssignment(int assignmentId, byte[][] data, string authToken) {
            base.Channel.SubmitAssignment(assignmentId, data, authToken);
        }
        
        public System.Threading.Tasks.Task SubmitAssignmentAsync(int assignmentId, byte[][] data, string authToken) {
            return base.Channel.SubmitAssignmentAsync(assignmentId, data, authToken);
        }
    }
}
